### ISSUE TITLE
error deployer not found git

### ISSUE THREAD

**Issue by AndyLZC** [hexojs/hexo-deployer-git#106]
This problem has been bothering me for several days, according to the Internet ,
```
 deploy:
   type: git
   repo: git@github.com:<username>/<username>.github.io.git
   branch: master
```
```
npm install hexo-deployer-git --save
```

but,it still show
```
error Deployer not found : git
```

who can help me to solve this problem?
