### ISSUE TITLE
Bad indentation of a mapping entry at line 91, column 18:  ignore_hidden: true

### ISSUE THREAD

**Issue by goshinh** [hexojs/hexo-deployer-git#108]
After Installing this plugin,I configured this plugin in _config.yml like this:
``` yaml
deploy:
- type: git
  repo: https://github.com/goshinh/goshinh.github.io
  branch: master
  message: 
- type: git
  repo: https://github.com/goshinh/goshinh.github.io
  branch: src
  extend_dirs: /
    ignore_hidden: false
    ignore_pattern:
       public: .
```
the result below with running hexo clear/g or d:
> $ hexo g
> FATAL bad indentation of a mapping entry at line 91, column 18:
>         ignore_hidden: false
>                      ^
> YAMLException: bad indentation of a mapping entry at line 91, column 18:
>         ignore_hidden: false
