### ISSUE TITLE
deployer ignores user's name & email specified in _config.yml deploy/name and deploy/email

### ISSUE THREAD

**Issue by desmond-dsouza** [hexojs/hexo-deployer-git#112]
I do not have global git user-name & user-email configured, but I do have this in my _config.yml:

```
deploy:
  type: git
  repo: git@github.com:desmond-dsouza/blog.git
  branch: gh-pages
  message: "update blog"
  name: Desmond
  email: <my email>
```

However, each time I run `hexo deploy` I get this message:

```
Committer: desmond <desmond@Air.local>
Your name and email address were configured automatically based
on your username and hostname.
```

The commit gets done using that incorrect name & email. Is this a bug?

I checked in `.deploy_git` and its `.git/config` does not contain any user name or email. It appears  like these lines https://github.com/hexojs/hexo-deployer-git/blob/master/lib/deployer.js#L73-L75 are supposed to add those to the `.git/config`.
