### ISSUE TITLE
Question about post_edit

### ISSUE THREAD

**Issue by jodumont** [hexojs/hexo-deployer-git#132]
Hi;

_the parameter `Post edit` in `Next Theme` refer me to this repo_

#### I have a hard time to understand how to define `subdirectory-name`based on this example:

```
post_edit:
  enable: true
  #url: https://github.com/myUser/myProject/tree/master/subdirectory-name # Link for view source.
  url: https://github.com/myUser/myProject/edit/master/subdirectory-name # Link for fork & edit.
```

I means I have "**posts**" in `./sources/_posts/en/` and `./sources/_posts/fr/` and "**pages**" in 
`./sources/en/` and `./sources/fr/`

#### I tried without success

`url: https://github.com/myUser/myProject/edit/master/source/:lang/`

## My 2 questions

1. Do my logical structure with post and page is fine or someones had bad experience with this and/or think another way is better ?

2. Do someones have an idea how to manage the URL parameter ?

#### Thanks for you opinion and you team work :+1:
