### ISSUE TITLE
Token deploy prompts for username

### ISSUE THREAD

**Issue by oliversturm** [hexojs/hexo-deployer-git#159]
I'm trying to deploy my hexo site to GitHub Pages. Right now I'm testing my setup locally, but I intend to use a CI setup once it works (probably using GitHub actions).

Based on the README, I included this block in my `_config.yml`:

```
deploy:
  type: git
  repo: https://github.com/<myusername>/<myrepo>.git
  branch: gh-pages
  token: $GITHUB_TOKEN
  name: <my "visible" name>
  email: <my email>
```

I created an access token in GitHub with the repo scope. Now I run the deployment from the command line to test it:

```
GITHUB_TOKEN=<my token> hexo deploy
```

The site is generated and I see git messages when everything is added to the new local repo. After this, I see a prompt:

```
Username for 'https://github.com': 
```

Why does this come up? Who is supposed to enter this username in a CI scenario? My local system is not configured to remember an HTTPS GitHub username, since I normally use SSH. But the CI system would obviously never know this username - how do I specify it? 

(I tried using the `name` setting in the config file as a test, but that doesn't work - looking at the code, it's clearly not intended for that purpose.)

I confirmed that if I enter the username manually, the password prompt appears next. At this point I have to enter the token again and everything works - but it appears that the token configuration in the config file is ignored entirely.

I'm sure I'm misunderstanding something... can anybody confirm that token deployment is supposed to work for my use case?

**Comment by oliversturm** [comment]
Update: I was looking at https://hexo.io/docs/one-command-deployment.html and I found this.

> You will be prompted with username and password of the target repository, unless you authenticate with a token or ssh key.

This is clear enough - I should not expect a prompt when using a token. Does that mean something is wrong with my configuration for the token, or the mechanism that reads it?

**Comment by SukkaW** [comment]
@oliversturm 

```bash
export GITHUB_TOKEN=<token>
```

Will it works?

**Comment by oliversturm** [comment]
@SukkaW That shouldn't be necessary - the syntax I'm using sets the environment variable without exporting it. Works like a charm, usually.

On the suspicion that the environment variable value is not found for some reason, I tried adding my token to `_config.yml` directly, but this doesn't change anything about the behavior I'm seeing.

**Comment by oliversturm** [comment]
So... reading the source code, I find that the token handling is exclusively implemented in [this function](https://github.com/hexojs/hexo-deployer-git/blob/a4d02c9be3636f2d2a46f143d7d1e94629dded24/lib/parse_config.js#L7). As far as I can see, this means that it can only be used with the config structure that has a `repo` object with a sub-property `url` - the other syntax variations use other execution paths that don't handle the `token` at all. How strange.

I'll try to change my config and update this issue.

**Comment by oliversturm** [comment]
With a different config structure it works correctly now:

```
deploy:
  type: git
  repo:
    github:
      url: https://github.com/<myusername>/<myrepo>.git
      branch: gh-pages
      token: $GITHUB_TOKEN
  name: <my "visible" name>
  email: <my email>
```

I'm leaving the issue open - I guess this should either be fixed in code or documented. 

At this point I'm only wondering how everybody else does this? I wouldn't normally use this config structure unless I was pushing to multiple repos, which seems like an edge case to me.
