### ISSUE TITLE
deployer not found git

### ISSUE THREAD

**Issue by xfqwdsj** [hexojs/hexo-deployer-git#174]
Configuration files and deployer are configured correctly
```yml
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

plugins:
- hexo-generator-feed
- hexo-generator-sitemap

feed:
	type: atom
	path: rss.xml
	limit: 20

sitemap:
	path: blog.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
	type: git
	repo: git@xfqwdsj:xfqwdsj/blog.git
	branch: master
```
