### ISSUE TITLE
multi-git-deployer go wrong

### ISSUE THREAD

**Issue by gejiawen** [hexojs/hexo-deployer-git#18]
```yml
deploy:
  type: git
  message: [message]
  repo: 
    github: <repository url>,[branch]
    gitcafe: <repository url>,[branch]
```

我采用如上的方式去配置`_config.yml`文件，目的就是想要同时推送到多个remote，悲剧的是，在推送时报错了。

报错信息跟[这个](https://github.com/hexojs/hexo-deployer-git/issues/2)很类似，不过我是在本地操作也是报错。

环境如下，

```
{ 'hexo-site': '0.0.0',
  npm: '3.4.1',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  icu: '56.1',
  modules: '47',
  node: '5.0.0',
  openssl: '1.0.2d',
  uv: '1.7.5',
  v8: '4.6.85.28',
  zlib: '1.2.8' }
```
