### ISSUE TITLE
Should dual git deployment be supported ?

### ISSUE THREAD

**Issue by icanfly** [hexojs/hexo-deployer-git#24]
for some reason, dual-git-deployment is very necessary.

**Comment by Xuanwo** [comment]
Well, It has already supported.

```
deploy:
  type: git
  message: [message]
  repo: 
    github: <repository url>,[branch]
    gitcafe: <repository url>,[branch]
```
