### ISSUE TITLE
How to remove stored username and personal access token?

### ISSUE THREAD

**Issue by jxpeng98** [hexojs/hexo-deployer-git#294]
Hello, 

Recently, I tried to change the deploy repo and token. I found a problem: 

The system will not require for username and password for push even if I only enter the repo and branch:
```
deploy:
  type: git
  repo: https://github.com/jxpeng98/blog
  branch: gh-pages
  message: "{{ now('YYYY-MM-DD HH:mm:ss') }}"
```

When I change the repo URL and branch with name and token, it will show the error code `403`. I tried to remove stored credential information from the system. However, it did not work.

May I know whether there is any way to erase stored information and let the terminal prompt enter the name and password again?
