### ISSUE TITLE
`hexo deploy` causing error occurred when `Clearing .deploy_git folder...`

### ISSUE THREAD

**Issue by jacklee981229** [hexojs/hexo-deployer-git#306]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behaviors
- Run `hexo deploy` without encounter any error, even with existence of `.deploy_git` folder.

## Actual behavior
- as mentioned in topic

## How to reproduce?

* Step1: run `hexo g -d`, the first time running without existence of `.deploy_git` folder shall be okay.
* Step2: run `hexo deploy` again, error occurs when `Clearing .deploy_git folder...`

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v18.14.2
9.5.1
```

**Your site `_config.yml`** (Optional)

```yaml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: John Doe
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: redefine

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
- type: git
  repo: git@github.com:xiiaojiun981229/xiiaojiun981229.github.io.git
  branch: master
  extend_dirs: /
  ignore_hidden: false
  ignore_pattern:
    public: .
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 C:\Users\jackj\source\repos\xiiaojiun981229.github.io
+-- hexo-deployer-git@4.0.0 (git+ssh://git@github.com/hexojs/hexo-deployer-git.git#f125535fb2477ab71702b9ca819223f715d7e628)
+-- hexo-generator-archive@2.0.0
+-- hexo-generator-category@2.0.0
+-- hexo-generator-index@3.0.0
+-- hexo-generator-tag@2.0.0
+-- hexo-renderer-ejs@2.0.0
+-- hexo-renderer-marked@6.0.0
+-- hexo-renderer-stylus@2.1.0
+-- hexo-server@3.0.0
+-- hexo-theme-redefine@1.1.6
`-- hexo@6.3.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "6.3.0"
  },
  "dependencies": {
    "hexo": "^6.3.0",
    "hexo-deployer-git": "github:hexojs/hexo-deployer-git",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.0.0",
    "hexo-renderer-stylus": "^2.1.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-redefine": "^1.1.6"
  }
}
```

## Others

```bash
PS C:\Users\jackj\source\repos\xiiaojiun981229.github.io> hexo d
INFO  Validating config
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\jackj\source\repos\xiiaojiun981229.github.io\.deploy_git\themes'
```

screenshot of my .deploy_git folder.
![image](https://user-images.githubusercontent.com/68312551/222936096-40012229-86cd-428e-b7d5-2d07bd7f9057.png)
Inside `.deploy_git` it has another `.deploy_git`, im not sure if this is why the bug occurred.
![image](https://user-images.githubusercontent.com/68312551/222936109-f4428f9f-31c3-4b11-b09b-280a042c2edc.png)

**Comment by uiolee** [comment]
obviously, now `hexo` workdir files in your `.deploy_git` folder.

One of the possible reasons is that you set the same repo and branch for workdir and pages.


```yaml
deploy:
- type: git
  repo: git@github.com:xiiaojiun981229/xiiaojiun981229.github.io.git
  branch: master
```
