### ISSUE TITLE
Resources are not deployed

### ISSUE THREAD

**Issue by bennyn** [hexojs/hexo-deployer-git#35]
Hello, 

I executed `hexo generate --deploy` today to deploy my page to: https://bennyn.github.io/internet-of-chili/

The command deployed the page (which is pretty cool) but all resources (like `bootstrap/css/bootstrap.min.css`) are missing. Maybe you can help me to find out why.

My deployment configuration is this:

**_config.yml**

```yml
deploy:
  type: git
  repo: git@github.com:bennyn/internet-of-chili.git
  branch: gh-pages
```

And I am using the [clean-blog](https://github.com/klugjo/hexo-theme-clean-blog) theme.

My project is located here:
- https://github.com/bennyn/internet-of-chili

Did I forgot to configure something? Because I can see that the expected `bootstrap` directory is missing in my `gh-pages` branch. :cry:
