### ISSUE TITLE
Deploy to master branch

### ISSUE THREAD

**Issue by Azard** [hexojs/hexo-deployer-git#45]
My repo save origin source Hexo project file at `Master` branch, and generated file at `gh-pages` branch.

When I update to the separated hexo-deployer-git, and run `hexo d` at my working directory at `Master` branch, it always push `.deploy_git` to origin master, not origin gh-pages.

**Comment by ottobonn** [comment]
Have you set the banch in your _config.yml?

It should look something like this:

```
deploy:
  type: git
  repo: your-repo-url
  branch: gh-pages
```

**Comment by Azard** [comment]
Yes, I set all right. But when I deploy, it always block at some steps.
Now, I write a `deploy.sh`
``` Shell
rm -rf deploy
git clone https://github.com/appetizerio/blog deploy
cd deploy && git checkout gh-pages && cd ..
hexo clean
hexo g
cd public && cp -r * ../deploy && cd ..
cd deploy && git add -A && cd ..
cd deploy && git commit -a -m "update" && cd ..
cd deploy && git push origin gh-pages --force && cd ..
```

**Comment by NoahDragon** [comment]
Can't reproduce your issue. Could you please provide your _config.yml?

**Comment by Azard** [comment]
https://github.com/Azard/blog
My blog source file in master branch, and deploy in gh-pages branch, it will block at deploy blocks, and our team blog(https://blog.appetizer.io/) also face this problem.

**Comment by NoahDragon** [comment]
Could you please change the following code in your _config.yml, and have a try.

Origin:
``` yaml
deploy:
  type: git
  repo:
    github: https://github.com/Azard/blog.git,gh-pages
```
To:
``` yaml
deploy:
  type: git
  repo: git@github.com:Azard/blog.git
  branch: gh-pages
```
