### ISSUE TITLE
when i was trying to deploy on git, i got this issue

### ISSUE THREAD

**Issue by pwchi** [hexojs/hexo-deployer-git#6]
INFO Deploying: git
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troublesho...
TypeError: undefined is not a function
at Object.exports.parse (/opt/hexo/node_modules/hexo-deployer-git/node_modules/swig/lib/parser.js:438:19)
at parse (/opt/hexo/node_modules/hexo-deployer-git/node_modules/swig/lib/swig.js:354:19)
at Object.precompile (/opt/hexo/node_modules/hexo-deployer-git/node_modules/swig/lib/swig.js:486:23)
at Object.compile (/opt/hexo/node_modules/hexo-deployer-git/node_modules/swig/lib/swig.js:606:16)
at commitMessage (/opt/hexo/node_modules/hexo-deployer-git/lib/deployer.js:95:15)
at Hexo.module.exports (/opt/hexo/node_modules/hexo-deployer-git/lib/deployer.js:21:17)
at Hexo.tryCatcher (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
at Hexo.<anonymous> (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
at /opt/hexo/node_modules/hexo/lib/plugins/console/deploy.js:56:28
at tryCatcher (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
at ReductionPromiseArray._promiseFulfilled (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/main/reduce.js:103:38)
at ReductionPromiseArray.init [as _init$] (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise_array.js:92:18)
at Promise._settlePromiseAt (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:528:21)
at Promise._settlePromises (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
at Async._drainQueue (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:177:16)
at Async._drainQueues (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:187:10)
at Immediate.Async.drainQueues [as _onImmediate] (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by Xuanwo** [comment]
yml文档？

**Comment by pwchi** [comment]
我只有修改 # Deployment 区段

```
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: John Doe
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: landscape

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/pwchi/pwchi.github.com.git
  branch: [branch]
  message: [message]
```

**Comment by Xuanwo** [comment]
```
deploy:
  type: git
  repo: https://github.com/pwchi/pwchi.github.com.git
  branch: [branch]
  message: [message]
```

[branch]应该填写master- -，然后[message]填写你想要的信息。。。
