### ISSUE TITLE
two deployer

### ISSUE THREAD

**Issue by muxiaobai** [hexojs/hexo-deployer-git#60]
I should how  to write when having two deplyer,

```
deploy:
  type: git
  repo: xxx
  branch: master
  message: Site updated:{{ now('YYYY-MM-DD HH:mm:ss') }}
deploy:
  type: othertype
```

when I write like this, I get a error,  “duplicated mapping key ” .
I don't know how to do ,I will modify some one deployer or not ?
and I know this not git deployer wrong. but  if we can do this better, why not ?

**Comment by NoahDragon** [comment]
You could set them in the _config.yml file as following:

```
deploy:
    - type: git
      repo: xxx
      branch: xxx
    - type: othertype
      settings: othersettings
```
