### ISSUE TITLE
deployer is not setup git correctly after I delete .deploy_git

### ISSUE THREAD

**Issue by Seraphli** [hexojs/hexo-deployer-git#66]
When running `hexo d`, the command line stop after input user name and password. And I check the configuration in `.deploy_git\.git\config`, and there is no repo config.

**Comment by Seraphli** [comment]
_config.yml in the hexo directory
```
deploy:
  type: git
  repo: https://github.com/Seraphli/seraphli.github.io.git
  branch: master
```
