### ISSUE TITLE
travis ci问题

### ISSUE THREAD

**Issue by willin** [hexojs/hexo-deployer-git#73]
```yml
deploy:
- type: git
  repo: https://${GH_TOKEN}@${GH_REF}
  branch: master
```

可否将系统变量读出来去部署,这样就可以直接部署了,而不用自己再去写一个shell脚本
