### ISSUE TITLE
extend_dirs not actually publishing anything 

### ISSUE THREAD

**Issue by jpeterson** [hexojs/hexo-deployer-git#78]
Hello,

I'm trying to use `extend_dirs` to publish a couple directories that live outside my hexo website (which is contained in a subdirectory of my main repo).

When I run `hexo deploy`, the directories I've identified are copied into the root of my website directory, but never get deployed. I think this is because only the `public` folder is being added to the `.deploy_git` directory. What is needed to actually deploy the contents of the `extend_dirs`?

I've included my file structure and deployment configuration below.

Thanks!

### File structure:
```
├─ repo
    ├─ docs
    ├─ src
    ├─ website
        ├─ public
        ├─ scaffolds
        ├─ source
        ├─ themes
        ├─ _config.yml
```

### _config.yml:
``` yaml
deploy:
  type: git
  repo: <repository url>
  branch: gh-pages
  message:
  extend_dirs:
    - ../docs
    - ../src
```

**Comment by jpeterson** [comment]
Taking a look at the source, I think this issue stems from the following line:

https://github.com/hexojs/hexo-deployer-git/blob/master/lib/deployer.js#L130

When `pathFn.join` encounters a `../` in `dir`, it outputs:

`extendDist === website/src` 

instead of 

`extendDist === website/.deploy_git/src`

**Comment by jpeterson** [comment]
### Workaround:

Set up two deploy configurations, where the first one references the true location of your external directories, and the second refers to those directories within the hexo folder (since the first deploy will have copied them there for you).

Note: I point the first deploy to a dummy branch called `temp`, but I think this could be just be the same as your real deployment branch since this deployment workflow will always execute the real one last.

``` yaml
deploy:
  - type: git
    repo: <repo>
    branch: temp
    extend_dirs:
      - ../src
      - ../docs
  - type: git
    repo: <repo>
    branch: gh-pages
    extend_dirs:
      - src
      - docs
```
