### ISSUE TITLE
如何在发布的时候忽略特定的文件夹

### ISSUE THREAD

**Issue by ThinkRealize** [hexojs/hexo-deployer-git#80]
我尝试了主页上的例子，但是没有作用，public 目录还是会被提交，只是 public 的子目录不会被发布主目录下。我的配置：
```
  - type: git
    repo: https://github.com/ThinkRealize/github-pages.git
    branch: master
    extend_dirs: /
    ignore_hidden: false,
    ignore_pattern: 
      public: .
```
是我对 ignore_pattern 的理解错误了？

**Comment by NoahDragon** [comment]
如果希望忽略public，可以使用
```
ignore_pattern: public
```

**Comment by 976717326** [comment]
请问，如果要忽略多个文件夹的话怎么处理呢？
根目录的 **`_confog.yml`** 文件是这样配置的：
```
deploy:
  - type: git
    repo: git@github.com:976717326/976717326.github.io.git
    branch: master
  - type: git
    repo: git@github.com:976717326/976717326.github.io.git
    branch: src
    extend_dirs: /
    ignore_hidden: false
    ignore_pattern:
        public: .
        cdn: .
```
网页正常发布没有问题，然而在src分支里面依然可以看到cdn文件夹，public文件夹倒是没有出现。
