### ISSUE TITLE
deploy to multiple account with username/password saved?

### ISSUE THREAD

**Issue by cutelittleturtle** [hexojs/hexo-deployer-git#83]
Hi, I am really new to Hexo. Is it possible to configure `_config.yaml` so I can set up multiple gituhub repositories (different accounts) ? 

Also is it possible to have the username/password saved for them so I can just run `hexo deploy` to deploy the same content to multiple github repositories?

Or I guess I can just write a script to force push the `public/` content into each repository? But I am worried about having two `.git` inside the directory. 

Thank you.

**Comment by NoahDragon** [comment]
The deployer git doesn't support username/password to auth, but you could set SSH key for those repos. Therefore, you could set the config file like the following:
```
deploy:
  - type: git
    username: username
    email: email
    repo: git@github.com:<username>/<username>.github.io.git
    branch: master
  - type: git
    username: username2
    email: email2
    repo: git@gitlab.com:<username>/<username>.github.io.git
    branch: master
```
