### ISSUE TITLE
只想发布某些文件到分支该怎么设置

### ISSUE THREAD

**Issue by mafeifan** [hexojs/hexo-deployer-git#84]
我只想把scaffolds，source，themes目录及.gitignore，_config.yml和package.json这些文件发布到resource分支中，该怎么写呢。

现在的写法是这样，仍然会把node_modules加到版本库中。

```
deploy: 
  - type: git
    repo: https://github.com/mafeifan/mafeifan.github.io
    branch: master
  - type: git
    repo: https://github.com/mafeifan/mafeifan.github.io
    branch: resource
    extend_dirs: /
    ignore_hidden: false
    ignore_pattern:
      public: .
      node_modules: .
```
