### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by ycf-FED** [hexojs/hexo-deployer-git#9]
提示 `ERROR Deployer not found: git`
配置里是有相应配置段的
```
deploy:
  type: git
  repo: https://github.com/ycf-FED/ycf-FED.github.io.git
  branch: master
```
