### ISSUE TITLE
ERROR Deployer not found git in windows 10

### ISSUE THREAD

**Issue by thinksource** [hexojs/hexo-deployer-git#90]
My platform is windows 10 with git command line already set in path:

my package.json file is:
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.3.9"
  },
  "dependencies": {
    "hexo": "^3.3.9",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  },
  "devDependencies": {
    "hexo-deployer-git": "git+https://github.com/hexojs/hexo-deployer-git.git"
  }
}
```
My _config.yaml file is:

```
...
deploy:
  type: git
  repo:  git+ssh://git@github.com/thinksource/thinksource.github.io.git
  branch: master
  name: foretribe
  email: foretribe@gmail.com
....
```

I try to run it by command line:
```
>hexo generate
>hexo deploy
```
The result is:

```
F:\work\thinksource.github.io>hexo deploy
ERROR Deployer not found: git
```
my git.exe is at:
```
C:\Program Files\Git\cmd
```
and it is already in the PATH variable.

this is my git command.
```
F:\work\thinksource.github.io>git --version
git version 2.8.1.windows.1
```
Does hexo-deployer-git still work or I miss some plugins.
