### ISSUE TITLE
Ignoring node_modules dir pushing sources

### ISSUE THREAD

**Issue by hejcz** [hexojs/hexo-deployer-git#94]
Hi!

First of all I really like this plugin! Great job! I'm trying to setup deploy to:
- publish public directory content to one repo
- save sources to another one

I'm using the example from the README, but I can't ignore node_modules directory which is in the same directory as for example "scaffolds" dir. I read the source but it doesn't seem there is some option to ignore specific dir. ignore_pattern and ignore_hidden are applied to specifi files names. Is it possible to ignore directory?

**Comment by hejcz** [comment]
After further investgation following setup seems to work as expected :)
```
deploy:
  - type: git
     repo: https://github.com/hejcz/static_content
  - type: git
    repo: https://github.com/hejcz/source
    extend_dirs: /
    ignore_pattern:
      /: "node_modules|public"
```
